app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session, jsonify, current_app, Response
from sqlalchemy.orm import joinedload
from sqlalchemy import text  # Add this import
from app import db
import json
from app.models import Faculty, Department, Staff, User, ActivityType
from werkzeug.security import generate_password_hash, check_password_hash
import os
from werkzeug.utils import secure_filename
from back_end_process.Pyhton_files.video_processing import StaffProcessor
from back_end_process.Pyhton_files.main import second_test_camera
import logging
from datetime import datetime, timedelta
from back_end_process.Pyhton_files.main import start_Presntation
from back_end_process.Pyhton_files.class_.paths import paths1
from back_end_process.Pyhton_files.class_.atendance import atendance

from threading import Thread
bp = Blueprint('main', __name__)

@bp.route('/')
def index():
    error = session.pop('error', None)
    return render_template('index.html', error=error)

@bp.route('/login', methods=['POST'])
def login():
    username = request.form.get('username')
    password = request.form.get('password')

    user = User.query.filter_by(username=username).first()
    if user:
        if user.state == 0:
            response = {'success': False, 'message': 'Your account is inactive.'}
        elif check_password_hash(user.password, password):
            session['username'] = user.username
            session['role'] = user.role
            session['user_id'] = user.id  # Store user id in session
            response = {'success': True, 'message': 'Login successful.', 'redirect': url_for('main.staff')}
        else:
            response = {'success': False, 'message': 'Invalid username or password.'}
    else:
        response = {'success': False, 'message': 'Invalid username or password.'}

    return jsonify(response)

@bp.route('/logout', methods=['POST'])
def logout():
    session.clear()
    return jsonify({'success': True, 'message': 'Logout successful'})

@bp.route('/check-session', methods=['GET'])
def check_session():
    authenticated = 'username' in session
    return jsonify({'authenticated': authenticated})

@bp.route('/get_user_info', methods=['GET'])
def get_user_info():
    if 'username' in session:
        user = User.query.filter_by(username=session['username']).first()
        if user:
            return jsonify({'username': user.name})
    return jsonify({'username': None})

@bp.route('/contact_us')
def contact_us():
    return render_template('contact_us.html')

@bp.route('/about_us')
def about_us():
    return render_template('about_us.html')

@bp.route('/home')
def home():
    return render_template('home.html')

@bp.route('/users')
def users():
    if 'role' not in session or session['role'] != 'admin':
        return redirect(url_for('main.index'))

    # Call the stored procedure using text()
    result = db.session.execute(text("CALL GetActiveUsers()"))
    users = result.fetchall()
    
    message = session.pop('message', None)
    message_type = session.pop('message_type', None)
    return render_template('users.html', users=users, message=message, message_type=message_type)

@bp.route('/update_user', methods=['POST'])
def update_user():
    if 'role' not in session or session['role'] != 'admin':
        return redirect(url_for('main.index'))
    
    user_id = request.form['id']
    name = request.form['name']
    username = request.form['username']
    password = request.form['password']
    role = request.form['role']
    
    # Hash the password if provided
    hashed_password = generate_password_hash(password) if password else None

    # Call the stored procedure using text()
    if hashed_password:
        db.session.execute(
            text("CALL UpdateUser(:id, :name, :username, :password, :role)"),
            {'id': user_id, 'name': name, 'username': username, 'password': hashed_password, 'role': role}
        )
    else:
        db.session.execute(
            text("CALL UpdateUser(:id, :name, :username, NULL, :role)"),
            {'id': user_id, 'name': name, 'username': username, 'role': role}
        )

    db.session.commit()

    session['message'] = 'User updated successfully.'
    session['message_type'] = 'success'
    
    return redirect(url_for('main.users'))

@bp.route('/delete_user', methods=['POST'])
def delete_user():
    if 'role' not in session or session['role'] != 'admin':
        return redirect(url_for('main.index'))

    user_id = request.form['id']

    # Call the stored procedure to delete the user
    result = db.session.execute(
        text("CALL DeleteUser(:id)"),
        {'id': user_id}
    )

    # Check the result to ensure the user was deleted
    if result.rowcount > 0:
        session['message'] = 'User deleted successfully.'
        session['message_type'] = 'success'
    else:
        session['message'] = 'User not found.'
        session['message_type'] = 'error'
    
    db.session.commit()

    return redirect(url_for('main.users'))

@bp.route('/register_user', methods=['POST'])
def register_user():
    if 'role' not in session or session['role'] != 'admin':
        return redirect(url_for('main.index'))

    name = request.form['name']
    username = request.form['username']
    password = generate_password_hash(request.form['password'])
    role = request.form['role']

    # Call the stored procedure to register the user
    db.session.execute(
        text("CALL RegisterUser(:name, :username, :password, :role)"),
        {'name': name, 'username': username, 'password': password, 'role': role}
    )
    db.session.commit()

    session['message'] = 'User registered successfully.'
    session['message_type'] = 'success'
    
    return redirect(url_for('main.users'))

#Staff part
@bp.route('/staff')
def staff():
    if 'role' not in session or session['role'] != 'admin':
        return redirect(url_for('main.index'))

    search_query = request.args.get('search')
    if search_query:
        staff_members = Staff.query.filter(
            Staff.state == True,
            (Staff.staff_name.ilike(f'%{search_query}%')) |
            (Staff.email.ilike(f'%{search_query}%'))
        ).all()
    else:
        staff_members = Staff.query.filter_by(state=True).all()

    faculties = Faculty.query.all()
    departments = Department.query.all()
    message = session.pop('message', None)
    message_type = session.pop('message_type', None)
    return render_template('staff.html', staff_members=staff_members, faculties=faculties, departments=departments, message=message, message_type=message_type)


@bp.route('/delete_staff', methods=['POST'])
def delete_staff():
    if 'role' not in session or session['role'] != 'admin':
        return redirect(url_for('main.index'))

    staff_id = request.form['id_staff']

    # Call the stored procedure to deactivate the staff member
    result = db.session.execute(
        text("CALL sp_delete_staff(:staffId)"),
        {'staffId': staff_id}
    )
    db.session.commit()

    # Delete images and labels
    StaffProcessor().delete_images_and_labels(staff_id)

    session['message'] = 'Staff deactivated successfully and all related data deleted.'
    session['message_type'] = 'success'
    return redirect(url_for('main.staff'))

@bp.route('/add_staff', methods=['POST'])
def add_staff():
    if 'role' not in session or session['role'] != 'admin':
        return redirect(url_for('main.index'))

    staff_name = request.form['name']
    phone = request.form['phone']
    email = request.form['email']
    gender = request.form['gender']
    id_department = request.form['department_id']
    add_by_user_id = session['user_id']

    try:
        # Call the stored procedure to add a new staff member
        db.session.execute(
            text("CALL sp_add_staff(:staffName, :phone, :email, :gender, :departmentId, :addedByUserId, @newStaffId)"),
            {
                'staffName': staff_name,
                'phone': phone,
                'email': email,
                'gender': gender,
                'departmentId': id_department,
                'addedByUserId': add_by_user_id
            }
        )

        # Commit the transaction to save the new staff member
        db.session.commit()

        # Fetch the new staff ID
        new_staff_id = db.session.execute(text("SELECT @newStaffId")).scalar()

        if new_staff_id is None:
            raise ValueError("Failed to retrieve the new staff ID.")

        # Process the video if provided
        if 'video' in request.files and request.files['video'].filename != '':
            video = request.files['video']
            video_path = f"app/videos/{new_staff_id}.mp4"
            video.save(video_path)

            # Process the video to extract images
            StaffProcessor().insert_staff(video_path, staff_name, new_staff_id)  
            if os.path.exists(video_path): 
                os.remove(video_path)

        session['message'] = 'Staff added successfully.'
        session['message_type'] = 'success'
    
    except Exception as e:
        logging.error(f"Error adding staff: {str(e)}")
        db.session.rollback()  # Roll back the transaction on error
        session['message'] = f'Error adding staff: {str(e)}'
        session['message_type'] = 'error'

    return redirect(url_for('main.staff'))

@bp.route('/update_staff', methods=['POST'])
def update_staff():
    try:
        # Ensure the user is an admin
        if 'role' not in session or session['role'] != 'admin':
            return redirect(url_for('main.index'))

        logging.debug(f"Form data: {request.form}")
        logging.debug(f"Files: {request.files}")

        staff_id = request.form['id_staff']
        staff = Staff.query.get(staff_id)

        if not staff:
            session['message'] = 'Staff not found.'
            session['message_type'] = 'error'
            return redirect(url_for('main.staff'))

        # Retrieve current values

app/templates/about_us.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Soran_Face</title>
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@48,400,0,0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/about_us_style.css') }}">
    <script src="{{ url_for('static', filename='js/index_script.js') }}" defer></script>
    <style>
        .error-message {
            color: red;
            font-family: "Open Sans", sans-serif;
        }
    </style>
</head>

<body>
    <header>
        <nav class="navbar">
            <span class="hamburger-btn material-symbols-rounded">menu</span>
            <a href="{{ url_for('main.index') }}" class="logo">
                <img src="{{ url_for('static', filename='imag/Soran_Logo.png') }}" alt="logo">
                <h2>Soran_Face</h2>
            </a>
            <ul class="links">
                <span class="close-btn material-symbols-rounded">close</span>
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
                <li><a href="{{ url_for('main.about_us') }}">About us</a></li>
                <li><a href="{{ url_for('main.contact_us') }}">Contact us</a></li>
            </ul>
            <button class="login-btn">LOG IN</button>
        </nav>
    </header>

    <div class="blur-bg-overlay"></div>
    <div class="form-popup">
        <span class="close-btn material-symbols-rounded">close</span>
        <div class="form-box login">
            <div class="form-details">
                <video autoplay muted loop class="background-video">
                    <source src="{{ url_for('static', filename='imag/animation.mp4') }}" type="video/mp4">
                </video>
                <h2>Welcome Back</h2>
            </div>
            <div class="form-content">
                <h2>LOGIN</h2>
                <form id="loginForm" method="POST">
                    <div class="input-field">
                        <input type="text" name="username" required>
                        <label>Username</label>
                    </div>
                    <div class="input-field">
                        <input type="password" name="password" required>
                        <label>Password</label>
                    </div>
                    <a href="{{ url_for('main.contact_us') }}" class="forgot-pass-link">Forgot password?</a>
                    <button type="submit">Log In</button>
                    <p id="errorMessage" class="error-message">{{ error }}</p>
                </form>
            </div>
        </div>
    </div>
    <section class="about-us">
        <div class="about">
            <h2>About Us</h2>
            <div class="images">
                <img src="{{ url_for('static', filename='imag/girl.jpg') }}" class="pic" />
                <img src="{{ url_for('static', filename='imag/mohamad.jpg') }}" class="pic" />
            </div>
            <div class="text">
                <h5>Front-end &amp; back-end Developer &amp; <span>Designer</span></h5>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Expedita natus ad sed harum itaque ullam enim
                    quas,
                    veniam accusantium, quia animi id eos adipisci iusto molestias asperiores explicabo cum vero atque amet
                    corporis! Soluta illum facere consequuntur magni. Ullam dolorem repudiandae cumque voluptate consequatur
                    consectetur, eos provident necessitatibus reiciendis corrupti!</p>
                <div class="data">
                    <a href="{{ url_for('main.contact_us') }}" class="hire">Contact Us</a>
                </div>
            </div>
        </div>
    </section>
    <footer class="footer">
        © 2023. All Rights Reserved. <a href="mailto:Soran_Face@idq">Soran_Face@idq</a>
    </footer>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const loginForm = document.getElementById('loginForm');
            const errorMessage = document.getElementById('errorMessage');

            loginForm.addEventListener('submit', function (event) {
                event.preventDefault(); // Prevent the form from submitting

                const formData = new FormData(loginForm);

                fetch('/login', {
                    method: 'POST',
                    body: formData,
                })
                    .then(response => response.json())
                    .then(data => {
                        if (data.success) {
                            window.location.href = "{{ url_for('main.home') }}"; // Redirect to home page
                        } else {
                            errorMessage.textContent = data.message; // Display error message
                        }
                    })
                    .catch(error => {
                        console.error('Error:', error);
                        errorMessage.textContent = 'An error occurred. Please try again.'; // Display generic error message
                    });
            });
        });
    </script>
</body>

</html>

app/templates/contact_us.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Contact_Us</title>
  <!-- Google Fonts Link For Icons -->
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@48,400,0,0">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" />
  <link rel="stylesheet" href="{{ url_for('static', filename='css/contact_us_style.css') }}">
  <script src="{{ url_for('static', filename='js/index_script.js') }}" defer></script>
  <style>
    .error-message {
      color: red;
      font-family: "Open Sans", sans-serif;
    }
  </style>
</head>

<body>
  <header>
    <nav class="navbar">
      <span class="hamburger-btn material-symbols-rounded">menu</span>
      <a href="{{ url_for('main.index') }}" class="logo">
        <img src="{{ url_for('static', filename='imag/Soran_Logo.png') }}" alt="logo">
        <h2>Soran_Face</h2>
      </a>
      <ul class="links">
        <span class="close-btn material-symbols-rounded">close</span>
        <li><a href="{{ url_for('main.index') }}">Home</a></li>
        <li><a href="{{ url_for('main.about_us') }}">About us</a></li>
        <li><a href="{{ url_for('main.contact_us') }}">Contact us</a></li>
      </ul>
      <button class="login-btn">LOG IN</button>
    </nav>
  </header>

  <div class="blur-bg-overlay"></div>
  <div class="form-popup">
    <span class="close-btn material-symbols-rounded">close</span>
    <div class="form-box login">
      <div class="form-details">
        <video autoplay muted loop class="background-video">
          <source src="{{ url_for('static', filename='imag/animation.mp4') }}" type="video/mp4">
        </video>
        <h2>Welcome Back</h2>
      </div>
      <div class="form-content">
        <h2>LOGIN</h2>
        <form id="loginForm" action="{{ url_for('main.login') }}" method="POST">
          <div class="input-field">
            <input type="text" name="username" required>
            <label>Username</label>
          </div>
          <div class="input-field">
            <input type="password" name="password" required>
            <label>Password</label>
          </div>
          <a href="{{ url_for('main.contact_us') }}" class="forgot-pass-link">Forgot password?</a>
          <button type="submit">Log In</button>
          <p id="errorMessage" class="error-message">{{ error_message }}</p>
        </form>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="content">
      <div class="left-side">
        <div class="address details">
          <i class="fas fa-map-marker-alt"></i>
          <div class="topic">Address</div>
          <div class="text-one">Iraq, Soran</div>
          <div class="text-two">Delzyan 06</div>
        </div>
        <div class="phone details">
          <i class="fas fa-phone-alt"></i>
          <div class="topic">Phone</div>
          <div class="text-one">+964 783 269 9909</div>
          <div class="text-two">+964 750 828 5828</div>
        </div>
        <div class="email details">
          <i class="fas fa-envelope"></i>
          <div class="topic">Email</div>
          <div class="text-one">ahmadtofeq192@gmail.com</div>
          <div class="text-two">mr5121@cs.soran.edu.iq</div>
        </div>
      </div>
      <div class="right-side">
        <div class="topic-text">Send us a message</div>
        <p>If you need help or any feedback or issue be free to tell us</p>
        <form action="#">
          <div class="input-box">
            <input type="text" placeholder="Enter your name" />
          </div>
          <div class="input-box">
            <input type="text" placeholder="Enter your email" />
          </div>
          <div class="input-box message-box">
            <textarea placeholder="Enter your message"></textarea>
          </div>
          <div class="button">
            <input type="button" value="Send Now" />
          </div>
        </form>
      </div>
    </div>
  </div>
  <footer class="footer">
    © 2023. All Rights Reserved. <a href="mailto:Soran_Face@idq">Soran_Face@idq</a>
  </footer>
  <script>
    document.addEventListener('DOMContentLoaded', function () {
      const loginForm = document.getElementById('loginForm');
      const errorMessage = document.getElementById('errorMessage');

      loginForm.addEventListener('submit', function (event) {
        event.preventDefault(); // Prevent the form from submitting

        const formData = new FormData(loginForm);

        fetch("{{ url_for('main.login')}}", {
          method: 'POST',
          body: formData,
        })
          .then(response => response.json())
          .then(data => {
            if (data.success) {
              window.location.href = "{{ url_for('main.home') }}"; // Redirect to home page
            } else {
              errorMessage.textContent = data.message; // Display error message
            }
          })
          .catch(error => {
            console.error('Error:', error);
            errorMessage.textContent = 'An error occurred. Please try again.'; // Display generic error message
          });
      });
    });
  </script>
</body>

</html>

app/templates/users.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/user.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/dialog.css') }}">
    <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>
    <title>Users</title>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            fetch("{{ url_for('main.check_session') }}", {
                method: 'GET',
                credentials: 'same-origin'
            })
                .then(response => {
                    if (!response.ok) {
                        throw new Error('Session check failed');
                    }
                    return response.json();
                })
                .then(data => {
                    if (!data.authenticated) {
                        window.location.href = "{{ url_for('main.home') }}";
                    }
                })
                .catch(error => {
                    console.error('Error checking session:', error);
                });
        });
    </script>
</head>

<body>
    <nav class="sidebar close">
        <header>
            <div class="image-text">
                <span class="image">
                    <img src="{{ url_for('static', filename='imag/soran.png') }}" alt="">
                </span>
                <div class="text logo-text">
                    <span class="name">Soran_Face</span>
                    <span class="profession" id="user-name">Management</span>
                </div>
            </div>
            <i class='bx bx-chevron-right toggle'></i>
        </header>
        <div class="menu-bar">
            <div class="menu">
                <ul class="menu-links">
                    <li class="nav-link">
                        <a href="{{ url_for('main.home') }}" data-page="home" class="act">
                            <i class='bx bx-home-alt icon'></i>
                            <span class="text nav-text">Dashboard</span>
                        </a>
                    </li>
                    <li class="nav-link">
                        <a href="{{ url_for('main.staff') }}" data-page="staff">
                            <i class='bx bx-user-check icon'></i>
                            <span class="text nav-text">Staff</span>
                        </a>
                    </li>
                    <li class="nav-link">
                        <a href="{{ url_for('main.conferences') }}" data-page="conferences">
                            <i class='bx bx-chalkboard icon'></i>
                            <span class="text nav-text">Activities</span>
                        </a>
                    </li>
                    <li class="nav-link">
                        <a href="{{ url_for('main.presentation') }}" data-page="r-conferences">
                            <i class='bx bx-registered icon'></i>
                            <span class="text nav-text">R-Activities</span>
                        </a>
                    </li>
                    <li class="nav-link">
                        <a href="{{ url_for('main.test_camera') }}" data-page="test-camera">
                            <i class='bx bx-video-recording icon'></i>
                            <span class="text nav-text">Test Camera</span>
                        </a>
                    </li>
                    <li class="nav-link">
                        <a href="{{ url_for('main.users') }}" data-page="users">
                            <i class='bx bx-user icon'></i>
                            <span class="text nav-text">Users</span>
                        </a>
                    </li>
                    <li class="nav-link">
                        <a href="{{ url_for('main.model_train') }}" data-page="model-train">
                            <i class='bx bx-cube-alt icon'></i>
                            <span class="text nav-text">Model Train</span>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="bottom-content">
                <li>
                    <a href="#" id="logoutBtn">
                        <i class='bx bx-log-out icon'></i>
                        <span class="text nav-text">Logout</span>
                    </a>
                </li>
                <li class="mode">
                    <div class="sun-moon">
                        <i class='bx bx-moon icon moon'></i>
                        <i class='bx bx-sun icon sun'></i>
                    </div>
                    <span class="mode-text text">Dark mode</span>
                    <div class="toggle-switch">
                        <span class="switch"></span>
                    </div>
                </li>
            </div>
        </div>
    </nav>
    <section class="home">
        <div class="page-content">
            <h2>Users</h2>
            <p>Manage users below.</p>
    
            {% if message %}
            <div class="popup {{ message_type }}">
                <p class="below">{{ message }}</p>
            </div>
            {% endif %}
    
            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Username</th>
                        <th>Role</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                    <tr>
                        <td>{{ user.id }}</td>
                        <td>{{ user.name }}</td>
                        <td>{{ user.username }}</td>
                        <td>{{ user.role }}</td>
                        <td>
                            <button class="update-btn" data-id="{{ user.id }}">Update</button>
                            <form action="{{ url_for('main.update_user') }}" method="post" class="user-form hide"
                                data-id="{{ user.id }}">
                                <input type="hidden" name="id" value="{{ user.id }}">
                                <label for="name">Name:</label>
                                <input type="text" id="name" name="name" value="{{ user.name }}" required>
                                <label for="username">Username:</label>
                                <input type="text" id="username" name="username" value="{{ user.username }}" required>
                                <label for="password">Password:</label>
                                <input type="password" id="password" name="password">
                                <label for="role">Role:</label>
                                <select id="role" name="role" required>
                                    <option value="user" {{ 'selected' if user.role=='user' else '' }}>User</option>
                                    <option value="admin" {{ 'selected' if user.role=='admin' else '' }}>Admin</option>
                                </select>
                                <button type="submit" name="update" class="btn-update">Update</button>
                            </form>
                            <form action="{{ url_for('main.delete_user') }}" method="post">
                                <input type="hidden" name="id" value="{{ user.id }}">
                                <button type="submit" name="delete" class="btn-delete">Delete</button>
                            </form>
                        </td>
                    </tr>
                    {% else %}
                    <tr>
                        <td colspan="5">No users found.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <!-- Register user form -->
            <div class="register-container">
                <button class="register-btn">
                    <i class='bx bx-plus'></i>
                </button>
                <div class="register-form hide">
                    <form id="register-user-form" action="{{ url_for('main.register_user') }}" method="post">
                        <div class="form-group">
                            <label for="name">Name:</label>
                            <input type="text" id="name" name="name" required>
                        </div>
                        <div class="form-group">
                            <label for="username">Username:</label>
                            <input type="text" id="username" name="username" required>
                        </div>
                        <div class="form-group">
                            <label for="password">Password:</label>
                            <input type="password" id="password" name="password" required>
                        </div>
                        <div class="form-group">
                            <label for="role">Role:</label>
                            <select id="role" name="role" required>
                                <option value="user">User</option>
                                <option value="admin">Admin</option>
                            </select>
                        </div>
                        <input type="submit" value="Register" class="submit-btn">
                    </form>
                </div>
            </div>
        </div>
    </section>
    <div id="deleteUserDialog" class="dialog hide">
    <div class="icon">&#10007;</div>
    <div class="message">Are you sure?</div>
    <div class="message">You will not be able to recover this User!</div>
    <button class="cancel">Cancel</button>
    <button class="delete">Delete!</button>
    </div>
    {% include 'dialog.html' %}
    <script src="{{ url_for('static', filename='js/users_script.js') }}"></script>
    <script src="{{ url_for('static', filename='js/dialog.js') }}"></script>
</body>
</html>